### ISSUE TITLE
SubfieldBase has been deprecated in Django 1.8

### ISSUE THREAD

**Issue by atul-bhouraskar** [mfogel/django-timezone-field#24] opened 2015-07-13 01:16 UTC
The `TimeZoneField` class uses `models.SubfieldBase` which is deprecated in Django 1.8 and will be removed in 1.10.

Django documentation reference is `https://docs.djangoproject.com/en/1.8/releases/1.8/#subfieldbase`

The use appears in `timezone_field/fields.py", line 100`

Discovered this in the process of upgrading to Django 1.8 as I run tests with `PendingDeprecationWarning` converted to errors.

I'm not familiar with this aspect of Django so haven't proposed a pull request.

Atul

**Comment by mfogel** [comment] 2015-08-02 21:56
Thanks for the heads up. I'm tempted to delay addressing this until I can drop support for django 1.6 _and_ django 1.7. Supporting both >=1.8 (not using SubfieldBase) and <1.8 (using SubfieldBase) sounds like a lot of work just to avoid a warning (but pull requests happily entertained :)

So, tentative schedule would be:

 * drop support for django 1.6 and south ASAP (as soon as at work we upgrade to 1.7...)
 * django project is scheduled to drop support for 1.7 and release 1.9 in December https://www.djangoproject.com/download/
 * shortly after that happens, this project will drop support for 1.7
 * at that point, I'll re-write stuff to support the new methods

This will allow the project to only support one implementation at a time - either the >=1.8 or the <1.8. Again - happy to support both simultaneously if someone provides a PR.

**Comment by 1337** [comment] 2015-12-02 03:06
Django 1.9 is released!

**Comment by kevin-brown** [comment] 2016-01-15 16:22
Just want to bring this up again, Django 1.7 is no longer officially supported.

**Comment by EyePulp** [comment] 2016-01-27 15:55
I *think* this is causing the six deprecation warning in my logs under Django 1.9.  Look forward to the fix, and appreciate the brighter minds willing to work on it.  Thank you!

**Comment by jaddison** [comment] 2016-01-29 18:25
I've been working on a fix for the SubfieldBase deprecation, but all fixes cause the tests to fail. I noticed that @michaeljones has also got a similar fix in his fork's `develop` branch here https://github.com/michaeljones/django-timezone-field/tree/develop - with the same test failures.

Something must have changed, because I think the changes are solid?

**Comment by ivanvenosdel** [comment] 2016-01-29 20:16
@jaddison Looking at the patches you linked, my suspicion is that the problem is caused by from_db_value being implemented in a manner identical to to_python instead of doing it's own thing. 

The example in [the Django documentation on the subject](https://docs.djangoproject.com/en/1.9/howto/custom-model-fields/#converting-values-to-python-objects) seems to imply subtle differences between where the methods are called and how they should handled. In particular I am seeing that the branch's implementation does not define the full signature for from_db_value.

`def from_db_value(self, value)`

instead of

`def from_db_value(self, value, expression, connection, context)`

**Comment by jaddison** [comment] 2016-01-29 20:26
I've tried following those examples from the Django docs with the same end result.

**Comment by jaddison** [comment] 2016-01-29 20:32
Both `to_python()` and `from_db_value()` are meant to return Python objects, which they do with @michaeljones' efforts.  The tests are failing because they seem to be operating on different (old? obsolete maybe?) assumptions.

**Comment by mfogel** [comment] 2016-01-29 20:32
I'll find time this weekend to review this PR and the forks/patches that have addressed this issue. Sorry for the slow movement here.

**Comment by michaeljones** [comment] 2016-01-30 13:20
I'm afraid my fork can't be taken as evidence in this situation. I dabbled with upgrading to Django-1.9 and so investigated this change due to the warning in 1.9 but I've since gone back to 1.8 and am not using this change. I'm afraid I haven't had the time to investigate it further. Plus the commit on my fork is from @arecker who deserve the credit for the work so far.

**Comment by jaddison** [comment] 2016-01-30 16:56
Fair enough, but my interpretation of the official way to implement this indicates that your fork has it implemented correctly. Hopefully @mfogel can figure out what's going on!

Thanks for being big enough to pass the credit on! :)

**Comment by mfogel** [comment] 2016-01-31 19:06
I've uploaded a new version to pypi that no longer uses SubfieldBase. It's version 2.0rc1.

This passes the test suite cleanly on django 1.8 and 1.9. However, at work (my primary real-life testbed for this app) we're still on django 1.8. So I'm not able to do the full regression I'd like to on django 1.9... if one of you folks who are running django 1.9 could try out 2.0rc1 and file and bugs/issues that come up, I'd appreciate it.

If no problems comes up in a week, I'll release the rc1 as '2.0' for reals next weekend.

**Comment by EyePulp** [comment] 2016-02-03 15:02
We upgraded in dev and in production yesterday.  Seems to be working okay under 1.9.

**Comment by ivanvenosdel** [comment] 2016-02-05 15:31
This is working well in our automated and manual tests. A subtle change I noticed from the 1.3 version that I think has more to do with Django than DTF.

In DTF 1.3 when the field was set it would return a DstTzInfo on the next getattr:
```python
>>> user.timezone = 'US/Eastern'
>>> user.timezone
<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>
```

In DTF 2.* when the field is set, the attr will still remain as is unless a fresh copy is retrieved from the DB.
```python
>>> user.timezone = 'US/Eastern'
>>> user.timezone
'US/Eastern'
>>> user.save()
>>> fresh_user = models.User.objects.get(pk=1)
>>> fresh_user.timezone
<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>
```

I personally don't see this as a problem and I actually find the new behaviour to be more intuitive. It is a change however so I thought it worth noting.

**Comment by jaddison** [comment] 2016-02-06 21:31
I'd think that it's supposed to be python objects, once the field is set?

**Comment by kevin-brown** [comment] 2016-02-07 02:21
> In DTF 2.* when the field is set, the attr will still remain as is unless a fresh copy is retrieved from the DB.

I think this behaviour is consistent with other Django fields? I vaguely remember hearing about this happening with the built-in `DecimalField`, because Django doesn't clean the values at all until it saves them to the database.

**Comment by ivanvenosdel** [comment] 2016-06-09 22:16
> if one of you folks who are running django 1.9 could try out 2.0rc1

I realize I neglected to mention that my testing was done with Django 1.9. Which looks good to us.

**Comment by Christophe31** [comment] 2016-08-02 08:44
it doesn't works with django 1.10 which released yesterday by the way…

**Comment by gschlabitz** [comment] 2016-08-02 16:26
@Christophe31 Have you tried version 2.0rc1? It seems to work fine for me in Django 1.10.

**Comment by Christophe31** [comment] 2016-08-02 16:58
indeed, you are right, pip install -U wasn't enough, I didn't searched. Should the 2.0rc1 be promoted 2.0?

**Comment by bgroff** [comment] 2016-08-10 00:57
I have also run into the issue of pip install pulling 1.3. Can the rc be promoted to 2.0? Seems like people are using it and it works as intended.

**Comment by pchinea** [comment] 2016-09-08 08:29
@mfogel Is there date for 2.0 releasing? Current stable version of django-timezone doesn't work with stable version of django.

**Comment by yonkornilov** [comment] 2016-09-09 21:00
pip install git + [REPO_URL]

**Comment by pchinea** [comment] 2016-09-10 08:26
@yonkornilov I know it, that's what i did to test it, but it is not suitable for a production environment, thanks anyway ;-)

**Comment by bgroff** [comment] 2016-09-10 14:39
I have packaged django-timezone-field-ng which is the current master branch, tagged as a 2.0 release on pip.

**Comment by mfogel** [comment] 2016-09-12 22:00
I just uploaded a 2.0 to pypi. It's exactly the same as the 2.0rc1 except for version string changes.

I've been MIA on maintaining this project. Sorry - I've been on you guys' side of this situation before and I know it's a frustrating situation. All you need is for the maintainer to do this one little thing...

I don't use this project myself anymore so it's hard to find time to work on it.

Does anyone want to take over maintenance of this project? I can transfer over ownership of the pypi repo to you and then you could release a v2.1 that identifies your fork as the primary repo.

**Comment by jaddison** [comment] 2016-09-15 02:24
What about the jazz band collection on GitHub?

https://github.com/jazzband

**Comment by kevin-brown** [comment] 2017-02-13 22:14
It looks like this has been fixed as of the 2.0 release (which wasn't tagged on GitHub).

**Comment by mfogel** [comment] 2018-02-28 22:14
It's tagged now, sorry for the oversight.

**Closed by mfogel** 2018-02-28 22:14 UTC

**Comment by dbinetti** [comment] 2018-09-12 16:15
Hey @mfogel we have all been there...  that said, how about transferring things to jazzband?
